"""Tiny result collector shared by the validators: PASS / WARN / FAIL / INFO rows,
a console summary, and a Markdown report in stress-tests/qa/."""

import sys
from datetime import date

from tokens import QA_DIR

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


class Report:
    def __init__(self, name, title, intro=""):
        self.name, self.title, self.intro = name, title, intro
        self.rows = []  # (status, check, detail)
        self.sections = []  # (heading, markdown)

    def add(self, status, check, detail=""):
        assert status in ("PASS", "WARN", "FAIL", "INFO"), status
        self.rows.append((status, check, detail))

    def ok(self, cond, check, detail="", fail="FAIL"):
        self.add("PASS" if cond else fail, check, detail)
        return cond

    def section(self, heading, markdown):
        self.sections.append((heading, markdown))

    def count(self, status):
        return sum(1 for r in self.rows if r[0] == status)

    @property
    def failed(self):
        return self.count("FAIL") > 0

    def summary(self):
        return (f"{self.title}: {self.count('PASS')} pass, {self.count('WARN')} warn, "
                f"{self.count('FAIL')} fail, {self.count('INFO')} info")

    def markdown(self):
        out = [f"# {self.title}", "",
               f"Generated by `tools/{self.name}.py` on {date.today().isoformat()}. Do not edit by hand.", ""]
        if self.intro:
            out += [self.intro, ""]
        out += [f"**Result: {'FAIL' if self.failed else 'PASS'}** ({self.summary().split(': ', 1)[1]})", ""]
        order = {"FAIL": 0, "WARN": 1, "PASS": 2, "INFO": 3}
        out += ["| Status | Check | Detail |", "|---|---|---|"]
        for status, check, detail in sorted(self.rows, key=lambda r: order[r[0]]):
            out.append(f"| {status} | {check} | {str(detail).replace('|', '/')} |")
        for heading, md in self.sections:
            out += ["", f"## {heading}", "", md]
        return "\n".join(out) + "\n"

    def write(self):
        QA_DIR.mkdir(parents=True, exist_ok=True)
        path = QA_DIR / f"{self.name}-report.md"
        path.write_text(self.markdown(), encoding="utf-8", newline="\n")
        return path

    def finish(self, verbose=True):
        path = self.write()
        if verbose:
            for status, check, detail in self.rows:
                if status in ("FAIL", "WARN"):
                    print(f"  {status}  {check}: {detail}")
        print(self.summary())
        print(f"  report: {path.relative_to(path.parents[2]).as_posix()}")
        return 1 if self.failed else 0
