// GENERATED by tools/build-web.py from system/tokens/tokens.json. Do not edit.
window.SYSTEM = {
 "generated": "GENERATED by tools/build-web.py from system/tokens/tokens.json. Do not edit.",
 "bpm": 120,
 "brand": {
  "red": "#D42A1E",
  "yellow": "#FFC20E",
  "ink": "#1C1410",
  "paper": "#FFF8EC"
 },
 "fonts": {
  "display": "Climate Crisis",
  "text": "Bricolage Grotesque",
  "hand": "Permanent Marker"
 },
 "chord": [
  "C2",
  "G2",
  "E3",
  "B3",
  "D4",
  "A4",
  "F#4"
 ],
 "personas": [
  {
   "id": "sprig",
   "name": "Sprig",
   "persona": "Conscious Upgrader",
   "number": "04",
   "order": 1,
   "time": "07:30",
   "light": "Cool morning daylight, fresh",
   "mascotImage": "assets/mascots/04-sprig.webp",
   "sceneImage": "assets/scenes/04-sprig-scene.webp",
   "threadForm": "vine",
   "packMechanic": "Half-sachet score line, add-in pictogram strip",
   "cardFront": "assets/cards/04-sprig-card-front.webp",
   "cardBack": "assets/cards/04-sprig-card-back.webp",
   "stickers": [
    "assets/stickers/04-sprig-sticker-fresh-add.webp",
    "assets/stickers/04-sprig-sticker-greens.webp",
    "assets/stickers/04-sprig-sticker-half-sachet.webp",
    "assets/stickers/04-sprig-sticker-my-two-minutes.webp",
    "assets/stickers/04-sprig-sticker-name.webp",
    "assets/stickers/04-sprig-sticker-wave.webp"
   ],
   "reactions": [
    "+greens",
    "half sachet",
    "fresh add"
   ],
   "motivation": "Health-compatible indulgence",
   "job": "Convenient meal with reduced guilt",
   "feltTime": "Two minutes to chop the greens in",
   "sachet": "Uses half, scored line, adds fresh ingredients",
   "spine": {
    "buyer": "Self",
    "eater": "Self",
    "socialUnit": "Solo or partner",
    "rhythm": "Planned",
    "gate": "\"Does this fit my goals?\""
   },
   "constraint": {
    "rule": "Natural paper texture, low-ink look",
    "why": "Honest, ingredient-forward"
   },
   "level": "AA",
   "palette": {
    "ink": "#26321F",
    "ink-muted": "#55604A",
    "paper": "#F2EDE1",
    "surface": "#E6DFCD",
    "leaf": "#6F8F5E",
    "olive": "#55603A",
    "wheat": "#D4BC86",
    "terracotta": "#B0452F",
    "mustard": "#C99B3A"
   },
   "pairs": [
    {
     "fg": "#26321F",
     "bg": "#F2EDE1",
     "fgName": "ink",
     "bgName": "paper",
     "use": "body",
     "where": "body copy",
     "ratio": 11.53
    },
    {
     "fg": "#26321F",
     "bg": "#E6DFCD",
     "fgName": "ink",
     "bgName": "surface",
     "use": "body",
     "where": "\"what's in your bowl\" label",
     "ratio": 10.14
    },
    {
     "fg": "#55604A",
     "bg": "#F2EDE1",
     "fgName": "ink-muted",
     "bgName": "paper",
     "use": "body",
     "where": "secondary copy",
     "ratio": 5.69
    },
    {
     "fg": "#55603A",
     "bg": "#F2EDE1",
     "fgName": "olive",
     "bgName": "paper",
     "use": "body",
     "where": "headings",
     "ratio": 5.76
    },
    {
     "fg": "#F2EDE1",
     "bg": "#55603A",
     "fgName": "paper",
     "bgName": "olive",
     "use": "body",
     "where": "reversed bands",
     "ratio": 5.76
    },
    {
     "fg": "#B0452F",
     "bg": "#F2EDE1",
     "fgName": "terracotta",
     "bgName": "paper",
     "use": "body",
     "where": "accent words",
     "ratio": 4.81
    },
    {
     "fg": "#6F8F5E",
     "bg": "#F2EDE1",
     "fgName": "leaf",
     "bgName": "paper",
     "use": "ui",
     "where": "pictogram strip, leaf icons (non-text)",
     "ratio": 3.12
    }
   ],
   "roles": {
    "bg": "#F2EDE1",
    "surface": "#E6DFCD",
    "text": "#26321F",
    "text-muted": "#55604A",
    "accent": "#B0452F",
    "line": "#26321F",
    "focus": "#55603A",
    "key": "#55603A",
    "sachet-red": "#B0452F",
    "sachet-yellow": "#C99B3A"
   },
   "type": {
    "display": "Fraunces",
    "text": "Karla",
    "ratio": 1.25
   },
   "stats": {
    "heat": 2,
    "speed": 3,
    "comfort": 3,
    "chaos": 1,
    "value": 2,
    "fancy": 3,
    "wellness": 5
   },
   "motion": {
    "tempo": "balanced",
    "idleBars": 2,
    "amplitude": 0.7,
    "squashStretch": 0,
    "accentBeats": [
     1,
     3
    ],
    "pulseHz": 0
   },
   "sound": {
    "pitch": "D4",
    "hz": 293.66,
    "palette": [
     "leaf rustle",
     "glass chime"
    ]
   },
   "product": {
    "name": "MAGGI Nutri-licious Veg Atta Noodles (2025 pack)",
    "format": "single pouch, 72.5 g",
    "why": "The variant an upgrader picks; Sprig still ADDS fresh greens (Section 18.13). Needs Nestle review: the pack sits close to health positioning; render any claim copy as illegible texture.",
    "image": "assets/packs/veg-atta-2025.webp",
    "oneInk": false
   },
   "mascot": {
    "concept": "A calm noodle sprout or bowl character with leaves, grains, and balanced proportions",
    "personality": "Mindful, fresh, composed, quietly optimistic"
   }
  },
  {
   "id": "stack",
   "name": "Stack",
   "persona": "Value-Stocking Homemaker",
   "number": "06",
   "order": 2,
   "time": "10:30",
   "light": "Neutral late-morning, busy",
   "mascotImage": "assets/mascots/06-stack.webp",
   "sceneImage": "assets/scenes/06-stack-scene.webp",
   "threadForm": "shelf rail",
   "packMechanic": "Tear-off Mon–Sun calendar on the multipack",
   "cardFront": "assets/cards/06-stack-card-front.webp",
   "cardBack": "assets/cards/06-stack-card-back.webp",
   "stickers": [
    "assets/stickers/06-stack-sticker-1-per-day.webp",
    "assets/stickers/06-stack-sticker-mon-sun.webp",
    "assets/stickers/06-stack-sticker-my-two-minutes.webp",
    "assets/stickers/06-stack-sticker-name.webp",
    "assets/stickers/06-stack-sticker-stocked.webp",
    "assets/stickers/06-stack-sticker-wave.webp"
   ],
   "reactions": [
    "STOCKED",
    "1 PER DAY",
    "MON-SUN"
   ],
   "motivation": "Household value and reliability",
   "job": "Pantry staple for predictable family meals",
   "feltTime": "Two minutes per serving, counted in rows",
   "sachet": "Counts them: one sachet per serving, in rows",
   "spine": {
    "buyer": "Planner",
    "eater": "Whole household",
    "socialUnit": "Household",
    "rhythm": "Bulk, scheduled",
    "gate": "Price per serving + availability"
   },
   "constraint": {
    "rule": "Strict grid, stamp and price-tag logic",
    "why": "Planning and counting"
   },
   "level": "AA",
   "palette": {
    "ink": "#14213D",
    "ink-muted": "#3A4763",
    "paper": "#F5EBD7",
    "label-white": "#FFFDF7",
    "kraft": "#C4A27A",
    "stamp": "#B3122B",
    "price-tag": "#FFC72C",
    "shelf-blue": "#1C5D99"
   },
   "pairs": [
    {
     "fg": "#14213D",
     "bg": "#F5EBD7",
     "fgName": "ink",
     "bgName": "paper",
     "use": "body",
     "where": "body copy",
     "ratio": 13.5
    },
    {
     "fg": "#14213D",
     "bg": "#C4A27A",
     "fgName": "ink",
     "bgName": "kraft",
     "use": "body",
     "where": "text on cardboard",
     "ratio": 6.69
    },
    {
     "fg": "#14213D",
     "bg": "#FFC72C",
     "fgName": "ink",
     "bgName": "price-tag",
     "use": "body",
     "where": "price-per-serving tags",
     "ratio": 10.24
    },
    {
     "fg": "#3A4763",
     "bg": "#F5EBD7",
     "fgName": "ink-muted",
     "bgName": "paper",
     "use": "body",
     "where": "secondary copy",
     "ratio": 7.85
    },
    {
     "fg": "#FFFDF7",
     "bg": "#B3122B",
     "fgName": "label-white",
     "bgName": "stamp",
     "use": "body",
     "where": "stamp reversals",
     "ratio": 6.8
    },
    {
     "fg": "#B3122B",
     "bg": "#F5EBD7",
     "fgName": "stamp",
     "bgName": "paper",
     "use": "body",
     "where": "stamp text on paper",
     "ratio": 5.84
    },
    {
     "fg": "#FFFDF7",
     "bg": "#1C5D99",
     "fgName": "label-white",
     "bgName": "shelf-blue",
     "use": "body",
     "where": "shelf strip labels",
     "ratio": 6.71
    }
   ],
   "roles": {
    "bg": "#F5EBD7",
    "surface": "#C4A27A",
    "text": "#14213D",
    "text-muted": "#3A4763",
    "accent": "#B3122B",
    "line": "#14213D",
    "focus": "#14213D",
    "key": "#1C5D99",
    "sachet-red": "#B3122B",
    "sachet-yellow": "#FFC72C"
   },
   "type": {
    "display": "Barlow Condensed",
    "text": "Barlow",
    "ratio": 1.333
   },
   "stats": {
    "heat": 2,
    "speed": 4,
    "comfort": 4,
    "chaos": 1,
    "value": 5,
    "fancy": 1,
    "wellness": 3
   },
   "motion": {
    "tempo": "rhythmic and exact",
    "idleBars": 1,
    "amplitude": 0.8,
    "squashStretch": 0.04,
    "accentBeats": [
     1,
     2,
     3,
     4
    ],
    "pulseHz": 0
   },
   "sound": {
    "pitch": "C2",
    "hz": 65.41,
    "palette": [
     "box stacking thuds",
     "calendar tick"
    ]
   },
   "product": {
    "name": "MAGGI 2-Minute Noodles Masala, 12-pack",
    "format": "multipack, 840 g (12 x 70 g)",
    "why": "Bulk, scheduled, price per serving. Built from the single Masala pack: stacked pouches in a multipack wrap.",
    "image": "assets/packs/masala-single.webp",
    "oneInk": false
   },
   "mascot": {
    "concept": "A dependable multipack-inspired pantry guardian character",
    "personality": "Organized, practical, warm, efficient"
   }
  },
  {
   "id": "cram",
   "name": "Cram",
   "persona": "Hostel Hungry",
   "number": "01",
   "order": 3,
   "time": "13:00",
   "light": "Flat fluorescent, hard shadows",
   "mascotImage": "assets/mascots/01-cram.webp",
   "sceneImage": "assets/scenes/01-cram-scene.webp",
   "threadForm": "zine underline",
   "packMechanic": "One-colour print, exam timetable on the sleeve",
   "cardFront": "assets/cards/01-cram-card-front.webp",
   "cardBack": "assets/cards/01-cram-card-back.webp",
   "stickers": [
    "assets/stickers/01-cram-sticker-2-min-done.webp",
    "assets/stickers/01-cram-sticker-brb-eating.webp",
    "assets/stickers/01-cram-sticker-my-two-minutes.webp",
    "assets/stickers/01-cram-sticker-name.webp",
    "assets/stickers/01-cram-sticker-no-dishes.webp",
    "assets/stickers/01-cram-sticker-wave.webp"
   ],
   "reactions": [
    "brb, eating",
    "2 min. done.",
    "no dishes"
   ],
   "motivation": "Lowest-effort filling meal",
   "job": "Cheapest, fastest filling meal during student life",
   "feltTime": "Counts it on a phone timer",
   "sachet": "Uses all of it, fast, no ceremony",
   "spine": {
    "buyer": "Self",
    "eater": "Self",
    "socialUnit": "Solo or roommates",
    "rhythm": "Impulse, small packs",
    "gate": "Price + zero cleanup"
   },
   "constraint": {
    "rule": "Strict black and white, one-colour print logic",
    "why": "Budget is the style"
   },
   "level": "AAA",
   "palette": {
    "ink": "#000000",
    "paper": "#FFFFFF",
    "screen-75": "#404040",
    "screen-50": "#808080",
    "screen-25": "#BFBFBF",
    "screen-10": "#E6E6E6"
   },
   "pairs": [
    {
     "fg": "#000000",
     "bg": "#FFFFFF",
     "fgName": "ink",
     "bgName": "paper",
     "use": "body",
     "where": "all body copy",
     "ratio": 21.0
    },
    {
     "fg": "#FFFFFF",
     "bg": "#000000",
     "fgName": "paper",
     "bgName": "ink",
     "use": "body",
     "where": "reversed headers, timetable bars",
     "ratio": 21.0
    },
    {
     "fg": "#000000",
     "bg": "#BFBFBF",
     "fgName": "ink",
     "bgName": "screen-25",
     "use": "body",
     "where": "text on yellow-half of sachet",
     "ratio": 11.42
    },
    {
     "fg": "#000000",
     "bg": "#E6E6E6",
     "fgName": "ink",
     "bgName": "screen-10",
     "use": "body",
     "where": "text on tinted panels",
     "ratio": 16.83
    },
    {
     "fg": "#FFFFFF",
     "bg": "#404040",
     "fgName": "paper",
     "bgName": "screen-75",
     "use": "body",
     "where": "reversed text on dark screen",
     "ratio": 10.37
    }
   ],
   "roles": {
    "bg": "#FFFFFF",
    "surface": "#E6E6E6",
    "text": "#000000",
    "text-muted": "#404040",
    "accent": "#000000",
    "line": "#000000",
    "focus": "#000000",
    "key": "#000000",
    "sachet-red": "#000000",
    "sachet-yellow": "#BFBFBF"
   },
   "type": {
    "display": "Archivo Black",
    "text": "IBM Plex Mono",
    "ratio": 1.414
   },
   "stats": {
    "heat": 2,
    "speed": 5,
    "comfort": 3,
    "chaos": 2,
    "value": 5,
    "fancy": 1,
    "wellness": 1
   },
   "motion": {
    "tempo": "tired but quick",
    "idleBars": 1,
    "amplitude": 1.1,
    "squashStretch": 0.12,
    "accentBeats": [
     1,
     3
    ],
    "pulseHz": 0
   },
   "sound": {
    "pitch": "B3",
    "hz": 246.94,
    "palette": [
     "kettle click",
     "fork tap",
     "phone timer blip"
    ]
   },
   "product": {
    "name": "MAGGI 2-Minute Noodles Masala",
    "format": "single pouch, 70 g",
    "why": "The default, cheapest single pack: Cram's 'all of it, fast' meal.",
    "image": "assets/packs/masala-single.webp",
    "oneInk": true
   },
   "mascot": {
    "concept": "A monochrome noodle-cup student creature with headphones, a backpack, and a fork",
    "personality": "Exhausted but resourceful, clever, always hungry"
   }
  },
  {
   "id": "nest",
   "name": "Nest",
   "persona": "Practical Parent",
   "number": "03",
   "order": 4,
   "time": "16:15",
   "light": "Warm afternoon sun",
   "mascotImage": "assets/mascots/03-nest.webp",
   "sceneImage": "assets/scenes/03-nest-scene.webp",
   "threadForm": "yarn",
   "packMechanic": "Draw-on-the-pack panel",
   "cardFront": "assets/cards/03-nest-card-front.webp",
   "cardBack": "assets/cards/03-nest-card-back.webp",
   "stickers": [
    "assets/stickers/03-nest-sticker-2-quiet-min.webp",
    "assets/stickers/03-nest-sticker-all-gone.webp",
    "assets/stickers/03-nest-sticker-half-for-you.webp",
    "assets/stickers/03-nest-sticker-my-two-minutes.webp",
    "assets/stickers/03-nest-sticker-name.webp",
    "assets/stickers/03-nest-sticker-wave.webp"
   ],
   "reactions": [
    "half for you",
    "all gone!",
    "2 quiet min"
   ],
   "motivation": "Kid-approved convenience",
   "job": "Reliable, kid-approved backup meal",
   "feltTime": "Gets two quiet minutes",
   "sachet": "Measures it carefully, often \"half for the little one\"",
   "spine": {
    "buyer": "Parent",
    "eater": "Child (and parent)",
    "socialUnit": "Household with kids",
    "rhythm": "Frequent top-ups",
    "gate": "The child says yes"
   },
   "constraint": {
    "rule": "No sharp corners, large touch targets",
    "why": "Safe, kid-near"
   },
   "level": "AA",
   "palette": {
    "ink": "#4A2A18",
    "ink-muted": "#7A5038",
    "paper": "#FFF3E0",
    "surface": "#FFE4BF",
    "tomato": "#BF3F2A",
    "honey": "#FFC94D",
    "peach": "#F6A58A",
    "sky": "#8CC7E6",
    "sage": "#9CBF8E"
   },
   "pairs": [
    {
     "fg": "#4A2A18",
     "bg": "#FFF3E0",
     "fgName": "ink",
     "bgName": "paper",
     "use": "body",
     "where": "body copy",
     "ratio": 11.71
    },
    {
     "fg": "#4A2A18",
     "bg": "#FFE4BF",
     "fgName": "ink",
     "bgName": "surface",
     "use": "body",
     "where": "cards, recipe panels",
     "ratio": 10.46
    },
    {
     "fg": "#7A5038",
     "bg": "#FFF3E0",
     "fgName": "ink-muted",
     "bgName": "paper",
     "use": "body",
     "where": "secondary copy",
     "ratio": 6.32
    },
    {
     "fg": "#BF3F2A",
     "bg": "#FFF3E0",
     "fgName": "tomato",
     "bgName": "paper",
     "use": "body",
     "where": "headings",
     "ratio": 4.84
    },
    {
     "fg": "#FFF3E0",
     "bg": "#BF3F2A",
     "fgName": "paper",
     "bgName": "tomato",
     "use": "body",
     "where": "buttons",
     "ratio": 4.84
    },
    {
     "fg": "#4A2A18",
     "bg": "#FFC94D",
     "fgName": "ink",
     "bgName": "honey",
     "use": "body",
     "where": "label bands",
     "ratio": 8.38
    },
    {
     "fg": "#4A2A18",
     "bg": "#8CC7E6",
     "fgName": "ink",
     "bgName": "sky",
     "use": "body",
     "where": "label bands",
     "ratio": 6.99
    }
   ],
   "roles": {
    "bg": "#FFF3E0",
    "surface": "#FFE4BF",
    "text": "#4A2A18",
    "text-muted": "#7A5038",
    "accent": "#BF3F2A",
    "line": "#4A2A18",
    "focus": "#BF3F2A",
    "key": "#FFC94D",
    "sachet-red": "#BF3F2A",
    "sachet-yellow": "#FFC94D"
   },
   "type": {
    "display": "Baloo 2",
    "text": "Nunito",
    "ratio": 1.25
   },
   "stats": {
    "heat": 1,
    "speed": 4,
    "comfort": 5,
    "chaos": 2,
    "value": 4,
    "fancy": 1,
    "wellness": 3
   },
   "motion": {
    "tempo": "smooth",
    "idleBars": 2,
    "amplitude": 0.9,
    "squashStretch": 0.06,
    "accentBeats": [
     1
    ],
    "pulseHz": 0
   },
   "sound": {
    "pitch": "G2",
    "hz": 98.0,
    "palette": [
     "kettle pour",
     "wooden spoon on pot"
    ]
   },
   "product": {
    "name": "MAGGI 2-Minute Noodles Veggie Masala",
    "format": "single pouch (top-up)",
    "why": "Familiar masala with visible vegetables: the pack a parent tops up and a child says yes to. No nutrition claim is made.",
    "image": "assets/packs/veggie-masala.webp",
    "oneInk": false
   },
   "mascot": {
    "concept": "A warm noodle-nest kitchen helper wearing an apron",
    "personality": "Caring, dependable, calm, slightly busy"
   }
  },
  {
   "id": "riot",
   "name": "Riot",
   "persona": "Maximalist Foodie",
   "number": "02",
   "order": 5,
   "time": "19:30",
   "light": "Colored practical lights, phone glow",
   "mascotImage": "assets/mascots/02-riot.webp",
   "sceneImage": "assets/scenes/02-riot-scene.webp",
   "threadForm": "flame hair",
   "packMechanic": "Peel-and-swap sticker sachet, deliberately misregistered print",
   "cardFront": "assets/cards/02-riot-card-front.webp",
   "cardBack": "assets/cards/02-riot-card-back.webp",
   "stickers": [
    "assets/stickers/02-riot-sticker-my-two-minutes.webp",
    "assets/stickers/02-riot-sticker-name.webp",
    "assets/stickers/02-riot-sticker-oil.webp",
    "assets/stickers/02-riot-sticker-remix.webp",
    "assets/stickers/02-riot-sticker-shoot-it.webp",
    "assets/stickers/02-riot-sticker-wave.webp"
   ],
   "reactions": [
    "REMIX!",
    "+OIL",
    "SHOOT IT"
   ],
   "motivation": "Flavor experimentation",
   "job": "Turns Maggi into a personalized flavor experiment",
   "feltTime": "Two minutes of remix: the build-and-shoot window before it goes soggy",
   "sachet": "Swaps, stacks, or replaces it with chili oil",
   "spine": {
    "buyer": "Self",
    "eater": "Self + an audience",
    "socialUnit": "Solo making, shared via feed",
    "rhythm": "Novelty-led",
    "gate": "\"Is this worth making and posting?\""
   },
   "constraint": {
    "rule": "Controlled clash: fixed rules for which colours may collide",
    "why": "Chaos with a grammar"
   },
   "level": "AA",
   "palette": {
    "ink": "#14101F",
    "paper": "#FFF6E0",
    "hot-pink": "#FF2E88",
    "acid-green": "#B8F200",
    "volt-blue": "#2B3DFF",
    "tangerine": "#FF6A13",
    "ultraviolet": "#7A2BF5",
    "yolk": "#FFD000",
    "chili": "#E8231A",
    "cyan": "#00D7F0"
   },
   "pairs": [
    {
     "fg": "#14101F",
     "bg": "#FFF6E0",
     "fgName": "ink",
     "bgName": "paper",
     "use": "body",
     "where": "captions, recipe steps",
     "ratio": 17.36
    },
    {
     "fg": "#14101F",
     "bg": "#FF2E88",
     "fgName": "ink",
     "bgName": "hot-pink",
     "use": "body",
     "where": "sticker text",
     "ratio": 5.34
    },
    {
     "fg": "#14101F",
     "bg": "#B8F200",
     "fgName": "ink",
     "bgName": "acid-green",
     "use": "body",
     "where": "sticker text",
     "ratio": 14.01
    },
    {
     "fg": "#FFF6E0",
     "bg": "#2B3DFF",
     "fgName": "paper",
     "bgName": "volt-blue",
     "use": "body",
     "where": "sticker text",
     "ratio": 6.07
    },
    {
     "fg": "#14101F",
     "bg": "#FF6A13",
     "fgName": "ink",
     "bgName": "tangerine",
     "use": "body",
     "where": "sticker text",
     "ratio": 6.52
    },
    {
     "fg": "#FFF6E0",
     "bg": "#7A2BF5",
     "fgName": "paper",
     "bgName": "ultraviolet",
     "use": "body",
     "where": "sticker text",
     "ratio": 5.59
    },
    {
     "fg": "#14101F",
     "bg": "#FFD000",
     "fgName": "ink",
     "bgName": "yolk",
     "use": "body",
     "where": "sticker text",
     "ratio": 12.7
    },
    {
     "fg": "#14101F",
     "bg": "#00D7F0",
     "fgName": "ink",
     "bgName": "cyan",
     "use": "body",
     "where": "sticker text",
     "ratio": 10.66
    },
    {
     "fg": "#14101F",
     "bg": "#E8231A",
     "fgName": "ink",
     "bgName": "chili",
     "use": "large",
     "where": "display words only on chili",
     "ratio": 4.17
    }
   ],
   "roles": {
    "bg": "#FFF6E0",
    "surface": "#FFD000",
    "text": "#14101F",
    "text-muted": "#7A2BF5",
    "accent": "#FF2E88",
    "line": "#14101F",
    "focus": "#2B3DFF",
    "key": "#FF2E88",
    "sachet-red": "#E8231A",
    "sachet-yellow": "#FFD000"
   },
   "type": {
    "display": "Bungee",
    "text": "Rubik",
    "ratio": 1.5
   },
   "stats": {
    "heat": 5,
    "speed": 3,
    "comfort": 2,
    "chaos": 5,
    "value": 3,
    "fancy": 2,
    "wellness": 1
   },
   "motion": {
    "tempo": "syncopated",
    "idleBars": 1,
    "amplitude": 1.4,
    "squashStretch": 0.18,
    "accentBeats": [
     1.5,
     3.5
    ],
    "pulseHz": 2
   },
   "sound": {
    "pitch": "F#4",
    "hz": 369.99,
    "palette": [
     "sizzle",
     "sticker pop",
     "record-scratch accent"
    ]
   },
   "product": {
    "name": "MAGGI Special Masala Noodles ('Spicy. Yummy.')",
    "format": "single pouch, 70 g",
    "why": "Spice and remixing. Swap in the 2026 MAGGI Spicy range (Spicy Cheesy / Garlic / Manchurian) if a pack photo is supplied; it is not on the official site.",
    "image": "assets/packs/special-masala.webp",
    "oneInk": false
   },
   "mascot": {
    "concept": "A chaotic chili-noodle character with mismatched features, flame hair, stickers, and bold patterns",
    "personality": "Loud, experimental, expressive, playful"
   }
  },
  {
   "id": "mise",
   "name": "Mise",
   "persona": "Premium Flavor Explorer",
   "number": "07",
   "order": 6,
   "time": "21:00",
   "light": "Low warm pendant light, rich shadows",
   "mascotImage": "assets/mascots/07-mise.webp",
   "sceneImage": "assets/scenes/07-mise-scene.webp",
   "threadForm": "chopstick-lifted ribbon",
   "packMechanic": "Separate finishing-oil sachet, foil accent",
   "cardFront": "assets/cards/07-mise-card-front.webp",
   "cardBack": "assets/cards/07-mise-card-back.webp",
   "stickers": [
    "assets/stickers/07-mise-sticker-chef-s-kiss.webp",
    "assets/stickers/07-mise-sticker-finishing-oil.webp",
    "assets/stickers/07-mise-sticker-mise-en-place.webp",
    "assets/stickers/07-mise-sticker-my-two-minutes.webp",
    "assets/stickers/07-mise-sticker-name.webp",
    "assets/stickers/07-mise-sticker-wave.webp"
   ],
   "reactions": [
    "mise en place",
    "chef's kiss",
    "+ finishing oil"
   ],
   "motivation": "Premium taste adventure",
   "job": "Occasional elevated noodle experience",
   "feltTime": "Treats it as mise en place",
   "sachet": "Dissolves it into broth, finishes with a second oil sachet",
   "spine": {
    "buyer": "Self",
    "eater": "Self + guests",
    "socialUnit": "Solo, couple, or hosting",
    "rhythm": "Occasional trade-up",
    "gate": "\"Is it worth paying more?\""
   },
   "constraint": {
    "rule": "Duotone plus one foil accent",
    "why": "Restraint signals quality"
   },
   "level": "AA",
   "palette": {
    "oxblood": "#4A1416",
    "cream": "#F4EBDC",
    "tint-80": "#6C3F3E",
    "tint-60": "#8E6A65",
    "tint-35": "#B9A097",
    "foil": "#C9A24A"
   },
   "pairs": [
    {
     "fg": "#F4EBDC",
     "bg": "#4A1416",
     "fgName": "cream",
     "bgName": "oxblood",
     "use": "body",
     "where": "body copy, dark editorial spreads",
     "ratio": 12.66
    },
    {
     "fg": "#4A1416",
     "bg": "#F4EBDC",
     "fgName": "oxblood",
     "bgName": "cream",
     "use": "body",
     "where": "body copy, light spreads",
     "ratio": 12.66
    },
    {
     "fg": "#C9A24A",
     "bg": "#4A1416",
     "fgName": "foil",
     "bgName": "oxblood",
     "use": "body",
     "where": "foil headings",
     "ratio": 6.24
    },
    {
     "fg": "#F4EBDC",
     "bg": "#6C3F3E",
     "fgName": "cream",
     "bgName": "tint-80",
     "use": "body",
     "where": "captions on tinted panels",
     "ratio": 7.35
    },
    {
     "fg": "#4A1416",
     "bg": "#B9A097",
     "fgName": "oxblood",
     "bgName": "tint-35",
     "use": "body",
     "where": "captions on light tint",
     "ratio": 6.09
    },
    {
     "fg": "#8E6A65",
     "bg": "#F4EBDC",
     "fgName": "tint-60",
     "bgName": "cream",
     "use": "large",
     "where": "pull quotes only",
     "ratio": 4.04
    }
   ],
   "roles": {
    "bg": "#4A1416",
    "surface": "#6C3F3E",
    "text": "#F4EBDC",
    "text-muted": "#B9A097",
    "accent": "#C9A24A",
    "line": "#8E6A65",
    "focus": "#C9A24A",
    "key": "#4A1416",
    "sachet-red": "#4A1416",
    "sachet-yellow": "#C9A24A"
   },
   "type": {
    "display": "Playfair Display",
    "text": "Libre Franklin",
    "ratio": 1.618
   },
   "stats": {
    "heat": 3,
    "speed": 2,
    "comfort": 3,
    "chaos": 2,
    "value": 1,
    "fancy": 5,
    "wellness": 3
   },
   "motion": {
    "tempo": "cinematic and precise",
    "idleBars": 2,
    "amplitude": 0.6,
    "squashStretch": 0,
    "accentBeats": [
     1
    ],
    "pulseHz": 0
   },
   "sound": {
    "pitch": "A4",
    "hz": 440.0,
    "palette": [
     "sauce pour",
     "chopstick tap",
     "light string"
    ]
   },
   "product": {
    "name": "MAGGI Korean BBQ Chicken Noodles",
    "format": "single pouch",
    "why": "The trade-up: Korean variants sit far above core packs on price (evidence log, Medium).",
    "image": "assets/packs/korean-bbq-chicken.webp",
    "oneInk": false
   },
   "mascot": {
    "concept": "A refined noodle character with chopsticks, global flavor accents, and editorial styling",
    "personality": "Curious, sophisticated, adventurous, tasteful"
   }
  },
  {
   "id": "lull",
   "name": "Lull",
   "persona": "Midnight Recharger",
   "number": "05",
   "order": 7,
   "time": "00:45",
   "light": "Blue-violet dark, single warm glow",
   "mascotImage": "assets/mascots/05-lull.webp",
   "sceneImage": "assets/scenes/05-lull-scene.webp",
   "threadForm": "steam",
   "packMechanic": "Glow-in-the-dark steam ink",
   "cardFront": "assets/cards/05-lull-card-front.webp",
   "cardBack": "assets/cards/05-lull-card-back.webp",
   "stickers": [
    "assets/stickers/05-lull-sticker-clocked-out.webp",
    "assets/stickers/05-lull-sticker-my-two-minutes.webp",
    "assets/stickers/05-lull-sticker-name.webp",
    "assets/stickers/05-lull-sticker-night-night.webp",
    "assets/stickers/05-lull-sticker-slurp.webp",
    "assets/stickers/05-lull-sticker-wave.webp"
   ],
   "reactions": [
    "clocked out",
    "slurp",
    "night night"
   ],
   "motivation": "Emotional decompression",
   "job": "Emotional reward after work, study, gaming, or shifts",
   "feltTime": "Stretches it into a ritual",
   "sachet": "Tears it slowly; the tear is part of the ritual",
   "spine": {
    "buyer": "Self",
    "eater": "Self",
    "socialUnit": "Solo",
    "rhythm": "Habitual, tied to a need state",
    "gate": "\"Do I need comfort right now?\""
   },
   "constraint": {
    "rule": "Luminance-capped dark, no pure white",
    "why": "Easy on tired eyes"
   },
   "level": "AA",
   "palette": {
    "night": "#121127",
    "surface": "#1D1B3A",
    "raised": "#2A2752",
    "text": "#E4DDF2",
    "text-muted": "#B3AACF",
    "glow": "#FFB866",
    "star": "#F0D58A",
    "dusk-violet": "#8C7BE0",
    "ember": "#E0663F"
   },
   "pairs": [
    {
     "fg": "#E4DDF2",
     "bg": "#121127",
     "fgName": "text",
     "bgName": "night",
     "use": "body",
     "where": "body copy",
     "ratio": 14.03
    },
    {
     "fg": "#E4DDF2",
     "bg": "#1D1B3A",
     "fgName": "text",
     "bgName": "surface",
     "use": "body",
     "where": "cards",
     "ratio": 12.54
    },
    {
     "fg": "#B3AACF",
     "bg": "#121127",
     "fgName": "text-muted",
     "bgName": "night",
     "use": "body",
     "where": "secondary copy",
     "ratio": 8.43
    },
    {
     "fg": "#B3AACF",
     "bg": "#2A2752",
     "fgName": "text-muted",
     "bgName": "raised",
     "use": "body",
     "where": "secondary copy on raised",
     "ratio": 6.33
    },
    {
     "fg": "#FFB866",
     "bg": "#121127",
     "fgName": "glow",
     "bgName": "night",
     "use": "body",
     "where": "warm headings",
     "ratio": 10.84
    },
    {
     "fg": "#121127",
     "bg": "#FFB866",
     "fgName": "night",
     "bgName": "glow",
     "use": "body",
     "where": "buttons",
     "ratio": 10.84
    },
    {
     "fg": "#8C7BE0",
     "bg": "#121127",
     "fgName": "dusk-violet",
     "bgName": "night",
     "use": "large",
     "where": "display only",
     "ratio": 5.31
    }
   ],
   "roles": {
    "bg": "#121127",
    "surface": "#1D1B3A",
    "text": "#E4DDF2",
    "text-muted": "#B3AACF",
    "accent": "#FFB866",
    "line": "#B3AACF",
    "focus": "#FFB866",
    "key": "#8C7BE0",
    "sachet-red": "#E0663F",
    "sachet-yellow": "#FFB866"
   },
   "type": {
    "display": "Quicksand",
    "text": "Atkinson Hyperlegible",
    "ratio": 1.2
   },
   "stats": {
    "heat": 2,
    "speed": 3,
    "comfort": 5,
    "chaos": 1,
    "value": 3,
    "fancy": 2,
    "wellness": 2
   },
   "motion": {
    "tempo": "slow breathing",
    "idleBars": 2,
    "amplitude": 0.6,
    "squashStretch": 0,
    "accentBeats": [
     1
    ],
    "pulseHz": 0.25
   },
   "sound": {
    "pitch": "E3",
    "hz": 164.81,
    "palette": [
     "low hum",
     "soft chime",
     "whispered ASMR layer"
    ]
   },
   "product": {
    "name": "MAGGI Masala Cuppa Noodles",
    "format": "cup",
    "why": "Solo, minimal cleanup, made in the cup: the late-night ritual. Steam leaves the cup as stars.",
    "image": "assets/packs/masala-cuppa.webp",
    "oneInk": false
   },
   "mascot": {
    "concept": "A sleepy moon-faced noodle bowl whose steam becomes stars",
    "personality": "Cozy, dreamy, gently humorous, comforting"
   }
  }
 ]
};
