"""Generate the live-clock page's data from tokens.json (never hand-edit the outputs).

    python tools/build-web.py

Writes into web/live-clock/:
  system.css          one [data-persona] block of CSS custom properties per persona
  system.js           window.SYSTEM = compact persona data (day windows, roles, type, motion, stats, product, ...)
  assets/packs/*      the persona pack images, copied from brief/references/packs/
  assets/mascots/*    die-cut hero cutouts (white outline and shadow baked in), WebP
  assets/scenes/*     the eating scenes with the real pack, WebP
  assets/cards/*      the collectible card fronts and backs and the shared card back (from cards/), WebP
  assets/stickers/*   the chat stickers (from stickers/), WebP
"""

import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "lib"))
import colour  # noqa: E402
import tokens as tk  # noqa: E402

WEB = tk.ROOT / "web" / "live-clock"
PACKS_SRC = tk.ROOT / "brief" / "references" / "packs"
PACKS_OUT = WEB / "assets" / "packs"
MASCOTS_OUT = WEB / "assets" / "mascots"
SCENES_OUT = WEB / "assets" / "scenes"
WEB_MAX_H = 800  # pack images show at most ~384 CSS px tall; 800 px covers 2x screens
NOTE_PC = {"C": 0, "C#": 1, "D": 2, "D#": 3, "E": 4, "F": 5, "F#": 6, "G": 7, "G#": 8, "A": 9, "A#": 10, "B": 11}
HEADER = "GENERATED by tools/build-web.py from system/tokens/tokens.json. Do not edit."


def hz(note):
    name, octave = note[:-1], int(note[-1])
    return round(440 * 2 ** ((12 * (octave + 1) + NOTE_PC[name] - 69) / 12), 2)


def v(tok):
    return tok["$value"] if isinstance(tok, dict) and "$value" in tok else tok


def font_stack(fams):
    return ", ".join(f'"{f}"' if " " in f or f[0].isupper() else f for f in fams)


def shadow(el, pid):
    kind = v(el["kind"])
    if kind == "none":
        return "none"
    col = v(el["color"]).lstrip("#")
    r, g, b = (int(col[i:i + 2], 16) for i in (0, 2, 4))
    return f"{v(el['x'])} {v(el['y'])} {v(el['blur'])} rgba({r}, {g}, {b}, {v(el['opacity'])})"


def css(res):
    out = [f"/* {HEADER} */"]
    for pid, p in tk.personas(res):
        roles, t, sh = tk.roles(p), p["type"], p["shape"]
        radii = sh["radius"]["$value"]
        lines = [
            *(f"  --{k}: {hexv};" for k, hexv in roles.items()),
            f"  --font-display: {font_stack(t['display']['$value'])};",
            f"  --font-text: {font_stack(t['text']['$value'])};",
            f"  --weight-display: {v(t['weight']['display'])};",
            f"  --weight-text: {v(t['weight']['text'])};",
            f"  --weight-strong: {v(t['weight']['text-strong'])};",
            f"  --lh-display: {v(t['line-height']['display'])};",
            f"  --lh-text: {v(t['line-height']['text'])};",
            f"  --track-display: {v(t['tracking']['display'])}em;",
            f"  --track-label: {v(t['tracking']['label'])}em;",
            f"  --case-display: {'none' if v(t['case']['display']) == 'small-caps' else v(t['case']['display'])};",
            f"  --style-display: {v(t['display-style']) if 'display-style' in t else 'normal'};",
            f"  --ratio: {v(t['scale-ratio'])};",
            f"  --radius: {radii[0]};",
            f"  --radius-large: {radii[-1] if radii[-1] != '999px' else radii[min(1, len(radii) - 1)]};",
            f"  --shadow: {shadow(p['elevation'], pid)};",
            f"  --tilt: {v(sh['angles']['rotation-max'])}deg;",
            f"  --beat: {res['motion']['clock']['beat']['$value']};",
            f"  --tempo-amplitude: {p['motion']['amplitude']};",
        ]
        out.append(f'[data-persona="{pid}"] {{\n' + "\n".join(lines) + "\n}")
    return "\n\n".join(out) + "\n"


def data(res):
    personas = []
    for pid, p in sorted(tk.personas(res), key=lambda kv: v(kv[1]["day"]["order"])):
        pal = tk.palette(p)
        names = {hexv.upper(): k for k, hexv in pal.items()}
        pairs = [{"fg": x["fg"], "bg": x["bg"], "fgName": names.get(x["fg"].upper(), x["fg"]),
                  "bgName": names.get(x["bg"].upper(), x["bg"]), "use": x["use"], "where": x["where"],
                  "ratio": round(colour.contrast(x["fg"], x["bg"]), 2)} for x in p["contrast"]["pairs"]]
        prod = p["product"]
        personas.append({
            "id": pid, "name": p["name"], "persona": p["persona"], "number": p["number"],
            "order": v(p["day"]["order"]), "time": p["day"]["time"], "light": p["day"]["light"],
            "mascotImage": f"assets/mascots/{p['number']}-{pid}.webp", "sceneImage": f"assets/scenes/{p['number']}-{pid}-scene.webp",
            "threadForm": p["noodleThread"], "packMechanic": p["packMechanic"]["concept"],
            "cardFront": f"assets/cards/{p['number']}-{pid}-card-front.webp", "cardBack": f"assets/cards/{p['number']}-{pid}-card-back.webp",
            "stickers": [f"assets/stickers/{f.stem}.webp" for f in sorted((tk.ROOT / "stickers" / p["slug"]).glob(f"{p['number']}-{pid}-sticker-*.png"))
                         if not f.stem.endswith("-sheet")],
            "reactions": v(p["stickers"]["reactions"]),
            "motivation": p["primaryMotivation"], "job": p["job"], "feltTime": p["feltTime"],
            "sachet": p["sachet"], "spine": p["spine"], "constraint": {"rule": p["constraint"]["rule"], "why": p["constraint"]["why"]},
            "level": p["contrast"]["level"], "palette": pal, "pairs": pairs, "roles": tk.roles(p),
            "type": {"display": p["type"]["display"]["$value"][0], "text": p["type"]["text"]["$value"][0],
                     "ratio": v(p["type"]["scale-ratio"])},
            "stats": p["stats"],
            "motion": {k: p["motion"][k] for k in ("tempo", "idleBars", "amplitude", "squashStretch", "accentBeats", "pulseHz")},
            "sound": {"pitch": p["sound"]["pitch"], "hz": hz(p["sound"]["pitch"]), "palette": p["sound"]["palette"]},
            "product": {"name": prod["name"], "format": prod["format"], "why": prod["why"],
                        "image": f"assets/packs/{web_name(prod['packImage'])}", "oneInk": pid == "cram"},
            "mascot": {"concept": p["mascot"]["concept"], "personality": p["mascot"]["personality"]},
        })
    ed = res["brand"]["type"]["editorial"]
    return {"generated": HEADER, "bpm": res["motion"]["clock"]["bpm"]["$value"],
            "brand": {k: v(res["brand"]["color"][k]) for k in ("red", "yellow", "ink", "paper")},
            "fonts": {k: v(ed[k])[0] for k in ("display", "text", "hand")},
            "chord": res["sound"]["chord"]["$value"], "personas": personas}


def web_name(name):
    """Every pack is published as a transparent WebP (JPEG backgrounds are cut first)."""
    return name.rsplit(".", 1)[0] + ".webp"


def cut_background(src, dst, tol=28):
    """Flood-fill the flat studio background from the image border to transparent (needs Pillow)."""
    from collections import deque
    from PIL import Image
    im = Image.open(src).convert("RGBA")
    w, h = im.size
    px = im.load()
    ref = [px[x, y] for x, y in ((0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1))]
    near = lambda c: any(sum(abs(c[i] - r[i]) for i in range(3)) <= tol * 3 for r in ref)
    seen = bytearray(w * h)
    q = deque((x, y) for x in range(w) for y in (0, h - 1)) + deque((x, y) for y in range(h) for x in (0, w - 1))
    while q:
        x, y = q.popleft()
        i = y * w + x
        if seen[i] or not near(px[x, y]):
            continue
        seen[i] = 1
        px[x, y] = (0, 0, 0, 0)
        for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nx < w and 0 <= ny < h and not seen[ny * w + nx]:
                q.append((nx, ny))
    bbox = im.getbbox()
    (im.crop(bbox) if bbox else im).save(dst)


def fit_for_web(src, dst, max_h=WEB_MAX_H):
    """Shrink to the page's largest display size at 2x and save as WebP with alpha (needs Pillow)."""
    from PIL import Image
    im = Image.open(src).convert("RGBA")
    if im.height > max_h:
        im = im.resize((round(im.width * max_h / im.height), max_h), Image.LANCZOS)
    im.save(dst, "WEBP", quality=86, method=6)


def publish_figures(res):
    """Mascot cutouts (same cut and die-cut bake as the PDF) and eating scenes, as WebP for the page."""
    import importlib.util
    import tempfile
    from PIL import Image
    spec = importlib.util.spec_from_file_location("build_pdf", Path(__file__).parent / "build-pdf.py")
    bp = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(bp)
    MASCOTS_OUT.mkdir(parents=True, exist_ok=True)
    SCENES_OUT.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix="web-"))
    for pid, p in tk.personas(res):
        st = tk.ROOT / "static" / p["slug"]
        cut = tmp / f"{pid}.png"
        bp.OV.cutout(st / f"{p['number']}-{pid}-hero-with-pack.png", cut)
        im = Image.open(cut)
        if im.height > 900:
            im = im.resize((round(im.width * 900 / im.height), 900), Image.LANCZOS)
        bp.bake_sticker(im, outline=8, pad=40, blur=14, dy=22, opacity=.38).save(
            MASCOTS_OUT / f"{p['number']}-{pid}.webp", "WEBP", quality=88, method=6)
        sc = Image.open(st / f"{p['number']}-{pid}-scene-with-pack.png").convert("RGB")
        sc.thumbnail((1280, 1280), Image.LANCZOS)
        sc.save(SCENES_OUT / f"{p['number']}-{pid}-scene.webp", "WEBP", quality=84, method=6)
    shutil.rmtree(tmp, ignore_errors=True)
    # collectible cards and stickers, made by tools/build-cards.py and tools/build-stickers.py
    cards_out, stick_out = WEB / "assets" / "cards", WEB / "assets" / "stickers"
    cards_out.mkdir(parents=True, exist_ok=True)
    stick_out.mkdir(parents=True, exist_ok=True)
    for src in list((tk.ROOT / "cards").glob("*/*-card-*.png")) + [tk.ROOT / "cards" / "card-back.png"]:
        if src.exists():
            im = Image.open(src).convert("RGBA")
            im.thumbnail((700, 980), Image.LANCZOS)
            im.save(cards_out / (src.stem + ".webp"), "WEBP", quality=86, method=6)
    for src in (tk.ROOT / "stickers").glob("*/*-sticker-*.png"):
        if not src.stem.endswith("-sheet"):
            im = Image.open(src).convert("RGBA")
            im.thumbnail((320, 320), Image.LANCZOS)
            im.save(stick_out / (src.stem + ".webp"), "WEBP", quality=86, method=6)


def main():
    res = tk.resolve_all(tk.load())
    WEB.mkdir(parents=True, exist_ok=True)
    (WEB / "system.css").write_text(css(res), encoding="utf-8", newline="\n")
    (WEB / "system.js").write_text(f"// {HEADER}\nwindow.SYSTEM = {json.dumps(data(res), ensure_ascii=False, indent=1)};\n",
                                   encoding="utf-8", newline="\n")
    PACKS_OUT.mkdir(parents=True, exist_ok=True)
    for _, p in tk.personas(res):
        src = PACKS_SRC / p["product"]["packImage"]
        if not src.exists():
            print(f"  missing pack image: {src.relative_to(tk.ROOT).as_posix()}")
        else:
            dst = PACKS_OUT / web_name(src.name)
            if src.suffix == ".png":
                shutil.copy2(src, dst.with_suffix(".png"))
                src_png = dst.with_suffix(".png")
            else:
                src_png = dst.with_suffix(".png")
                cut_background(src, src_png)
            fit_for_web(src_png, dst)
            src_png.unlink()
    publish_figures(res)
    print("  wrote web/live-clock/system.css, system.js, assets/packs/, assets/mascots/, assets/scenes/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
