"""Run every validator and write stress-tests/qa/summary.md.

    python tools/run-all.py

Exit code 1 if any validator fails. Python 3.10+, standard library only.
"""

import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHECKS = [
    ("check-tokens", "Token schema + semantics"),
    ("check-contrast", "WCAG contrast (AA, AAA for Cram)"),
    ("check-cvd", "Colour-blind simulation"),
    ("check-names", "File naming + folder structure"),
    ("check-rig", "Rig spec"),
    ("check-silhouettes", "Silhouette lineup (Gate 1 A)"),
    ("check-glyphs", "'2' glyphs (Gate 1 B)"),
    ("check-artwork", "Artwork colours + safety"),
    ("check-motion", "Motion clips"),
    ("check-web", "Live-clock page"),
    ("check-docs", "Persona Markdown files"),
    ("check-heroes", "3D toy heroes (series lineup + silhouettes)"),
]


def main():
    rows, failed = [], False
    for script, label in CHECKS:
        proc = subprocess.run([sys.executable, str(ROOT / "tools" / f"{script}.py")], cwd=ROOT,
                              capture_output=True, text=True, encoding="utf-8")
        print(f"== {label}")
        print(proc.stdout.rstrip())
        if proc.stderr.strip():
            print(proc.stderr.rstrip())
        m = re.search(r"(\d+) pass, (\d+) warn, (\d+) fail, (\d+) info", proc.stdout)
        counts = m.groups() if m else ("?", "?", "?", "?")
        ok = proc.returncode == 0
        failed |= not ok
        rows.append(f"| {label} | `tools/{script}.py` | {'PASS' if ok else '**FAIL**'} | {' | '.join(counts)} | "
                    f"[report]({script}-report.md) |")
    summary = ["# QA summary", "", f"Generated by `tools/run-all.py` on {date.today().isoformat()}.", "",
               "| Validator | Script | Result | Pass | Warn | Fail | Info | Detail |",
               "|---|---|---|---|---|---|---|---|", *rows, ""]
    (ROOT / "stress-tests" / "qa" / "summary.md").write_text("\n".join(summary), encoding="utf-8", newline="\n")
    print("\nALL CHECKS:", "FAIL" if failed else "PASS")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
